name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rebuild and restart containers
        run: |
          docker compose down
          docker compose build --no-cache
          docker compose up -d
